[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["trentprynn <trentprynn@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
start = "scripts.start:main"
lint = "scripts.lint:main"
create-migration = "scripts.create_migration:main"
migrate = "scripts.migrate:main"
seed = "scripts.seed:main"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.30"
alembic = "^1.13.1"
aiocache = "^0.12.2"
uvicorn = "^0.30.1"
fastapi = "^0.111.0"
psycopg = "^3.1.18"
pydantic = "^2.6.4"
pydantic-settings = "^2.2.1"
tenacity = "^8.2.3"
structlog = "^24.1.0"
beautifulsoup4 = "^4.12.3"
requests = "^2.31.0"
redis = "^5.0.3"
pendulum = "^3.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.4.8"
types-beautifulsoup4 = "^4.12.0"
types-requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
