"""add radio station

Revision ID: 01a7d2c14ac7
Revises: 
Create Date: 2024-03-23 14:43:01.564395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01a7d2c14ac7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radio_station",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("stream_url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index("idx_name", "radio_station", ["name"], unique=True)
    op.create_index(
        op.f("ix_radio_station_name"), "radio_station", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_radio_station_name"), table_name="radio_station")
    op.drop_index("idx_name", table_name="radio_station")
    op.drop_table("radio_station")
    # ### end Alembic commands ###
