"""add radio station playlist columns

Revision ID: 0313f809008e
Revises: 01a7d2c14ac7
Create Date: 2024-04-07 09:25:43.404721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0313f809008e"
down_revision: Union[str, None] = "01a7d2c14ac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

radio_station_playlist_type_enum = postgresql.ENUM(
    "SPINITRON", name="radio_station_playlist_type"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    radio_station_playlist_type_enum.create(op.get_bind())

    op.add_column(
        "radio_station",
        sa.Column("playlist_type", radio_station_playlist_type_enum, nullable=True),
    )
    op.add_column(
        "radio_station", sa.Column("playlist_url", sa.String(), nullable=True)
    )
    op.alter_column(
        "radio_station", "display_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "radio_station", "stream_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "radio_station", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "radio_station", "image_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "radio_station", "image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "radio_station", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "radio_station", "stream_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "radio_station", "display_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("radio_station", "playlist_url")
    op.drop_column("radio_station", "playlist_type")

    radio_station_playlist_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
