"""remove playlist type

Revision ID: 0a5a8faf2463
Revises: 7b80750833db
Create Date: 2024-05-15 11:16:10.915388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a5a8faf2463"
down_revision: Union[str, None] = "7b80750833db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radio_station", "playlist_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "radio_station",
        sa.Column(
            "playlist_type",
            postgresql.ENUM("SPINITRON", "KEXP", name="radio_station_playlist_type"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
