"""add radio station seo fields

Revision ID: 2752e073052a
Revises: f98303e42941
Create Date: 2026-05-10 16:55:59.041641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2752e073052a"
down_revision: Union[str, None] = "f98303e42941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "radio_station",
        sa.Column("long_description", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("call_sign", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("frequency", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("city", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("region", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("country", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("website_url", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("format", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("tagline", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("seo_title", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column("seo_description", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "radio_station",
        sa.Column(
            "content_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.alter_column("radio_station", "long_description", server_default=None)
    op.alter_column("radio_station", "call_sign", server_default=None)
    op.alter_column("radio_station", "frequency", server_default=None)
    op.alter_column("radio_station", "city", server_default=None)
    op.alter_column("radio_station", "region", server_default=None)
    op.alter_column("radio_station", "country", server_default=None)
    op.alter_column("radio_station", "website_url", server_default=None)
    op.alter_column("radio_station", "format", server_default=None)
    op.alter_column("radio_station", "tagline", server_default=None)
    op.alter_column("radio_station", "seo_title", server_default=None)
    op.alter_column("radio_station", "seo_description", server_default=None)
    op.alter_column("radio_station", "content_updated_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radio_station", "content_updated_at")
    op.drop_column("radio_station", "seo_description")
    op.drop_column("radio_station", "seo_title")
    op.drop_column("radio_station", "tagline")
    op.drop_column("radio_station", "format")
    op.drop_column("radio_station", "website_url")
    op.drop_column("radio_station", "country")
    op.drop_column("radio_station", "region")
    op.drop_column("radio_station", "city")
    op.drop_column("radio_station", "frequency")
    op.drop_column("radio_station", "call_sign")
    op.drop_column("radio_station", "long_description")
    # ### end Alembic commands ###
