"""add_starting_volume

Revision ID: 9ce480b0af96
Revises: eb62494eee8d
Create Date: 2025-01-18 23:22:33.185911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce480b0af96'
down_revision: Union[str, None] = 'eb62494eee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('starting_volume', sa.Integer(), server_default=sa.text('50'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'starting_volume')
    # ### end Alembic commands ###
